-- Create products table
CREATE TABLE IF NOT EXISTS public.products (
    id text PRIMARY KEY,
    title text NOT NULL,
    tag text NOT NULL,
    size_category text NOT NULL,
    dims text NOT NULL,
    price text NOT NULL,
    min_order integer NOT NULL,
    default_thickness text NOT NULL,
    "desc" text NOT NULL,
    specs text[] NOT NULL,
    images text[] NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable row-level security for products (allow public read, admin write)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public read access" ON public.products;
CREATE POLICY "Allow public read access" ON public.products FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow admin write access" ON public.products;
CREATE POLICY "Allow admin write access" ON public.products FOR ALL USING (auth.role() = 'authenticated');

-- Create orders table
CREATE TABLE IF NOT EXISTS public.orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id text NOT NULL,
    product_title text NOT NULL,
    length integer NOT NULL,
    width integer NOT NULL,
    height integer NOT NULL,
    quantity integer NOT NULL,
    board_type text NOT NULL,
    status text DEFAULT 'Pending'::text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable row-level security for orders (allow public insert, admin read/write)
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow public insert access" ON public.orders;
CREATE POLICY "Allow public insert access" ON public.orders FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Allow admin read/write access" ON public.orders;
CREATE POLICY "Allow admin read/write access" ON public.orders FOR ALL USING (auth.role() = 'authenticated');

-- Insert initial products data
INSERT INTO public.products (id, title, tag, size_category, dims, price, min_order, default_thickness, "desc", specs, images) VALUES
('mailer', 'Mailer Box', 'Mailer box', 'small', '150 × 100 × 50 mm', '₹9', 100, '3-Ply Standard', 'Perfect for jewelry, cosmetics, and small D2C shipments. Made from lightweight yet durable 3-ply kraft corrugated board. Custom printing options are available for wholesale orders. Designed to assemble quickly and ship safely without tape.', ARRAY['3-ply corrugated board, 300 GSM kraft paper', 'Matte rustic kraft or plain clean brown finish', 'Self-locking tuck flap, completely tape-free assembly', '100% biodegradable and recycled material'], ARRAY['https://images.pexels.com/photos/8015700/pexels-photo-8015700.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://images.pexels.com/photos/8015783/pexels-photo-8015783.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://images.pexels.com/photos/8015781/pexels-photo-8015781.jpeg?auto=compress&cs=tinysrgb&w=800']),
('gift', 'Gift & Jewelry Box', 'Gift box', 'small', '120 × 120 × 60 mm', '₹22', 50, '3-Ply Standard', 'Premium rigid setup gift box. Widely used for luxury wedding favors, festive gift hampers, jewelry packaging, and premium product giveaways. Features a stiff, heavy-duty cardboard core for ultimate crush-resistance.', ARRAY['Rigid cardboard chipboard core, 1200 GSM thickness', 'Magnetic flap closure options', 'Custom lamination and debossing available on wholesale', 'Velvet-lined foam and die-cut dividers on request'], ARRAY['https://images.pexels.com/photos/6119143/pexels-photo-6119143.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://images.pexels.com/photos/264771/pexels-photo-264771.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://images.pexels.com/photos/264917/pexels-photo-264917.jpeg?auto=compress&cs=tinysrgb&w=800']),
('shipping', 'Shipping Carton', 'Shipping carton', 'medium', '300 × 220 × 180 mm', '₹28', 50, '5-Ply Heavy', 'Our bestselling medium-sized shipper boxes. Specifically designed to withstand typical courier handling, transit vibrations, and drop impacts. Ideal for shipping apparel stacks, footwear, electronics, and books.', ARRAY['5-ply double-wall corrugated structure', 'Heavy test kraft liners with vertical wave-fluting', 'Accepts heavy-weight taping securely', 'Fits securely inside standard plastic courier bags'], ARRAY['https://images.pexels.com/photos/7464209/pexels-photo-7464209.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://images.pexels.com/photos/7464972/pexels-photo-7464972.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://images.pexels.com/photos/4498136/pexels-photo-4498136.jpeg?auto=compress&cs=tinysrgb&w=800']),
('apparel', 'Apparel Folding Box', 'Apparel box', 'medium', '330 × 250 × 80 mm', '₹18', 100, '3-Ply Standard', 'Pop-up folding apparel box designed specifically for clothing items like sarees, shirts, linens, and garments. Ships folded completely flat to save on warehousing footprint and snaps open in a few seconds.', ARRAY['3-ply lightweight folding design, space-saving', 'Bleached white liner or plain classic kraft option', 'Convenient tuck-in lid closure, no tape needed', 'Provides a clean canvas for screen printing designs'], ARRAY['https://images.pexels.com/photos/7410461/pexels-photo-7410461.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://images.pexels.com/photos/7410459/pexels-photo-7410459.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://images.pexels.com/photos/7410458/pexels-photo-7410458.jpeg?auto=compress&cs=tinysrgb&w=800']),
('heavyduty', 'Heavy-Duty Box', 'Heavy duty', 'large', '450 × 350 × 300 mm', '₹54', 25, '7-Ply Heavy Duty', 'Sturdy 7-ply heavy industrial packaging box. Engineered for shipping machine components, tools, metallic hardware parts, bulk supplies, and household electronics safely without structural bowing.', ARRAY['7-ply triple fluting double-wall heavy board', 'Stitch-welded or reinforced corner seams', 'Safely handles load weights up to 25 kg', 'Moisture-resistant kraft outer lining'], ARRAY['https://images.pexels.com/photos/10834810/pexels-photo-10834810.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://images.pexels.com/photos/906494/pexels-photo-906494.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://images.pexels.com/photos/10834813/pexels-photo-10834813.jpeg?auto=compress&cs=tinysrgb&w=800']),
('bulk', 'Bulk & Pallet Box', 'Bulk pallet', 'large', '600 × 400 × 400 mm', '₹89', 20, '7-Ply Heavy Duty', 'Extra large bulk shipping box designed to align perfectly with standard truck loads and wooden pallets. Highly suitable for commercial supply chains, cargo moves, exports, and heavy agricultural shipments.', ARRAY['Pallet-stackable volume proportions', 'Super thick double-wall board structure', 'Double layer stitched base options', 'Specifically reinforced bottom corners to prevent stack slips'], ARRAY['https://images.pexels.com/photos/29653988/pexels-photo-29653988.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://images.pexels.com/photos/29653989/pexels-photo-29653989.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://images.pexels.com/photos/172074/pexels-photo-172074.jpeg?auto=compress&cs=tinysrgb&w=800'])
ON CONFLICT (id) DO NOTHING;
